[workspace]
members = [
    "res_emulator",
    "res_egui",
    "res_libretro",
]

# Opt-level impact on execution time of nestest.nes
# 0 => 1182us
# 1 => 126us
# 2 => 128us
# 3 => 124us
# 3 + pgo => 124us
[profile.dev]
opt-level = 1
